// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs7jb7GTDkaIyCLJI9KmEorPC1wxZ9-Yc',
    appId: '1:487683231109:web:040a4ec186bfd381c508ec',
    messagingSenderId: '487683231109',
    projectId: 'vetcare-app-2025',
    authDomain: 'vetcare-app-2025.firebaseapp.com',
    storageBucket: 'vetcare-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATjk8rScMDcGco2LLqL7VXlLNBdhP8jgU',
    appId: '1:487683231109:android:6645dd19ed827a57c508ec',
    messagingSenderId: '487683231109',
    projectId: 'vetcare-app-2025',
    storageBucket: 'vetcare-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSezPF-OcpBcj3Da63XE3iS18llltOHMg',
    appId: '1:487683231109:ios:de220f932d645e20c508ec',
    messagingSenderId: '487683231109',
    projectId: 'vetcare-app-2025',
    storageBucket: 'vetcare-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.vetcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSezPF-OcpBcj3Da63XE3iS18llltOHMg',
    appId: '1:487683231109:ios:de220f932d645e20c508ec',
    messagingSenderId: '487683231109',
    projectId: 'vetcare-app-2025',
    storageBucket: 'vetcare-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.vetcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs7jb7GTDkaIyCLJI9KmEorPC1wxZ9-Yc',
    appId: '1:487683231109:web:abda2b6ded18988bc508ec',
    messagingSenderId: '487683231109',
    projectId: 'vetcare-app-2025',
    authDomain: 'vetcare-app-2025.firebaseapp.com',
    storageBucket: 'vetcare-app-2025.firebasestorage.app',
  );

}